#!/bin/bash

# Sauvegarde un historique des commits    
read -p "Sauvegarder un suivi du commit (y/[n]) ?" yn < /dev/tty
yn=${yn:n} 
case $yn in
        [Yy]* )
        echo "commit vérifié le $(date)" >> suivi/commitInfo.txt
                exit 0;;
        [Nn]* )
                exit 0;;
esac  
exit 0
